version: '3.6'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: hysryt/wordpress-for-mailcatcher:4.9.8-php7.2-apache
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

  wordmove:
    tty: true
    image: welaika/wordmove:latest
    restart: always
    volumes:
      - ./wordpress:/var/www/html
  
  smtp:
    image: schickling/mailcatcher
    ports:
      - '1080:1080'